[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
corda_notary = "E5Znp7prsJFLy9k4BgfUCe61wDqeDjTvVeW7EA5fGNVr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
